
export const prajwalResume = {
    name: 'Prajwal Sharma',
    linkedIn: 'LinkedIn',
    email: 'itspraz81@gmail.com',
    phone: '+1-562-440-6266',
    personalWebsite: 'https://prazwal.vercel.app',
    github: 'GitHub',
    education: {
        degree: 'Bachelor of Science in Computer Science',
        gpa: 'GPA: 3.67',
        graduation: 'Expected Graduation: May 2025',
        school: 'California State University, Long Beach – Long Beach, CA',
        courses: [
            'Computer Science Theory',
            'Object-Oriented Programming',
            'Data Structures & Algorithms',
            'Databases',
            'Software Engineering',
            'Operating Systems',
        ],
    },
    experience: {
        position: 'Founder',
        company: 'Better Grades Effortlessly 24/7',
        date: 'August 2021 – December 2023',
        description:
            'Built a scalable peer-to-peer tutoring platform using Next.js, AWS Lambda, and PostgreSQL, enabling efficient real-time interactions and handling thousands of concurrent users. Scaled to 6,000 monthly active users and 50 tutors, achieving over $120,000 in revenue within the first year with a 95% user satisfaction rate. Optimized platform performance by reducing load times by 30% using GraphQL and AWS services.',
    },
    projects: [
        {
            name: 'Mad Molecool',
            technologies: ['Gemini API', 'Intel OpenVINO'],
            frameworks: ['Python', 'TensorFlow'],
            description:
                'LLM-powered electronic lab notebook for molecular biologists. Features a fine-tuned lab partner, autogenerated summaries, and a chemical encyclopedia. Optimized LLMs using BF16 data type and INT8 quantization, enhancing performance on Intel CPU architecture.',
            awards: ['1st Place, UC Davis Hackathon 2024'],
        },
        {
            name: 'ASL Bridgify',
            technologies: ['PyTorch', 'TensorFlow', 'Keras', 'MediaPipe'],
            frameworks: ['Next.js', 'TailwindCSS', 'Flask'],
            description:
                'Innovative ASL learning platform leveraging AI for real-time feedback and personalized learning paths. Implemented hand pose estimation and trained LLMs on Intel Developer Cloud. Integrated RAG techniques using Google Search and OpenAI APIs.',
            awards: ['$25K Grand Prize, UC Berkeley Hackathon 2024'],
        },
        {
            name: 'NextSocial',
            technologies: ['MongoDB', 'Firebase', 'Next-Auth'],
            frameworks: ['NextJS','React', 'Tailwind CSS'],
            description: '🚀 NextSocial - A dynamic social media platform powered by NextJS, Tailwind CSS, MongoDB, and Firebase.\n\n🌐 Built with NextJS\'s App Router for seamless navigation.\n🎨 Stylish and responsive UI design crafted with Tailwind CSS.\n📊 MongoDB integration for efficient and scalable database management.\n🔥 Firebase utilized for secure and scalable image storage.\n🔐 Seamless authentication powered by next-auth for a hassle-free user experience.\n\n🚧 Under active development. Contributions welcome!\n\n🌟 Showcases:',
        },
        {
            name: 'Budget Pal',
            technologies: ['JavaScript', 'Python', 'HTML', 'CSS'],
            frameworks: ['Flask', 'Firebase'],
            description: 'Developed a receipt tracking platform that extracted and categorized information from user-uploaded receipts with 90% accuracy by preprocessing images with OpenCV to improve Google Tesseract’s OCR engine. Implemented the Google Maps API to pinpoint transaction locations and compare prices across retailers online through e-commerce APIs, resulting in a 95% average cost saving for users. Protected user data security by integrating Firebase’s SSO, enabling secure user login and access to a dashboard that visualizes financial data from the previously uploaded receipts.',
        },
        {
            name: 'Class Finder',
            technologies: ['JavaScript', 'Python', 'HTML'],
            frameworks: ['React', 'TailwindCSS', 'Flask', 'BeautifulSoup', 'Vercel'],
            description: 'Improved the CSULB class selection platform by incorporating modern design elements and reusable components, enhancing the user experience for over 5000 students with positive feedback. Optimized system processing for class selection by developing an API that aggregated over 1000 different classes, including class details, sections, and professor ratings.',
        },
        {
            name: 'EmergenSync',
            technologies: ['JavaScript', 'HTML', 'CSS'],
            frameworks: ['React', 'Node', 'Firebase', 'AWS Lambda'],
            description: 'Collaborated with a team of 4 to create an emergency room management tool for paramedics that enhanced ambulance routing and hospital room assignment processes. Improved patient information processing speed by 50% by implementing a live data transmission system via Firebase, ensuring hospital room statuses are updated in under 2 seconds. Enabled paramedics to identify optimal hospitals from 8 different metrics including ETA, distance, and room availability by creating an AWS Lambda-hosted API integrating Google Maps geocoding with patient data.',
        },
        {
            name: 'Job4Job',
            technologies: ['JavaScript', 'Python', 'HTML', 'CSS'],
            frameworks: ['React', 'Flask', 'TailwindCSS', 'Supabase'],
            description: 'Utilized CRUD operations to develop a service exchange platform for users to post and apply for service jobs within 30 seconds of a posting. Implemented a job match percentage based on user location and job skills by utilizing a weighted model and the Google Maps API, resulting in a 25% satisfaction rating with service workers.',
        },
    ],
    technicalSkills: {
        languages: ['Python', 'TypeScript', 'JavaScript', 'Java', 'C++', 'HTML', 'SQL', 'Go'],
        frameworks: ['React.js', 'Next.js', 'Node.js', 'Express.js', 'Flask', 'TailwindCSS'],
        libraries: ['TensorFlow', 'PyTorch', 'BeautifulSoup', 'Redux', 'Apollo GraphQL'],
        databases: ['MongoDB', 'Firebase', 'PostgreSQL', 'Redis', 'Supabase', 'Convex'],
        tools: ['AWS', 'Vercel', 'GitHub', 'Docker', 'Postman', 'Google API', 'AWS Lambda'],
    },
};
